### summary
- numpy : 선형대수를 빠르게 연산해주는 패키지
- 행열의 생성 1 : ndarray, np.array(literable)
- 행열의 생성 2 : ones, zeros
- 행열 데이터 선택 : array[x,y,z]
- 행열 데이터 수정
    - 행열 데이터를 선택
    - =, > (값(scala, vector, matrix))
    - 브로드 캐스팅 개념
- arrange : list에서 사용하는 range : 결과가 ndarray

### Quiz 
- 100~130까지 랜덤한 숫자를 가지는 8*8행렬을 만들고, 
- 3의 배수는 fiz, 5의 배수는 buz, 3과 5의 배수는 fbz문자로 변환
- 위의 조건에 맞지 않는 데이터는 랜덤하게 생성된 정수로 출력
- 랜덤한 행렬 데이터

```
datas = np.randome.randint(100,130, size = (8,8))
```
- 데이터 타입이 정수 -> 문자열: ndarray.astype()

In [4]:
import numpy as np

In [6]:
datas = np.random.randint(100,130, size = (8,8))
datas

array([[112, 114, 124, 122, 127, 120, 125, 105],
       [115, 106, 123, 123, 114, 112, 117, 104],
       [109, 103, 115, 110, 104, 123, 101, 119],
       [125, 110, 126, 122, 116, 116, 122, 110],
       [128, 123, 120, 119, 128, 122, 107, 121],
       [116, 119, 103, 123, 101, 100, 118, 108],
       [114, 114, 102, 102, 115, 111, 126, 100],
       [117, 113, 109, 108, 111, 106, 127, 101]])

In [11]:
data1 = np.array([1,2,3])
data2 = [True, False, True]
data1[data2]

array([1, 3])

In [20]:
# 3의 배수, 5의 배수, 15의 배수 위치값에 대한 T,Fmatrix 생성
idx_3 = datas % 3 == 0
idx_5 = datas % 5 == 0
idx_15 = datas % 15 == 0

In [22]:
# 데이터의 타입을 str으로 변환
datas.dtype

dtype('int32')

In [23]:
result = datas.astype("str")
result

array([['112', '114', '124', '122', '127', '120', '125', '105'],
       ['115', '106', '123', '123', '114', '112', '117', '104'],
       ['109', '103', '115', '110', '104', '123', '101', '119'],
       ['125', '110', '126', '122', '116', '116', '122', '110'],
       ['128', '123', '120', '119', '128', '122', '107', '121'],
       ['116', '119', '103', '123', '101', '100', '118', '108'],
       ['114', '114', '102', '102', '115', '111', '126', '100'],
       ['117', '113', '109', '108', '111', '106', '127', '101']],
      dtype='<U11')

In [14]:
# T,F matrix를이용하여 특정 조건의 데이터를 선택 후 브로드캐스팅하게 값을 대입

In [29]:
result[idx_3] = "fiz"
result[idx_5] = "buz"
result[idx_15] = "fbz"
result

array([['112', 'fiz', '124', '122', '127', 'fbz', 'buz', 'fbz'],
       ['buz', '106', 'fiz', 'fiz', 'fiz', '112', 'fiz', '104'],
       ['109', '103', 'buz', 'buz', '104', 'fiz', '101', '119'],
       ['buz', 'buz', 'fiz', '122', '116', '116', '122', 'buz'],
       ['128', 'fiz', 'fbz', '119', '128', '122', '107', '121'],
       ['116', '119', '103', 'fiz', '101', 'buz', '118', 'fiz'],
       ['fiz', 'fiz', 'fiz', 'fiz', 'buz', 'fiz', 'fiz', 'buz'],
       ['fiz', '113', '109', 'fiz', 'fiz', '106', '127', '101']],
      dtype='<U11')

### Quiz
- 1~20까지 랜덤한 숫자를 가지는 5*5행렬 생성
- 최대값에는 Max, 최소값에는 Min 문자열이 들어가도록 치환하는 코드
- 최대값과 최솟값 함수

```
np.min(ndarray), np.max(ndarray)
```

In [89]:
datas = np.random.randint(1,20, size = (5,5))
datas

array([[10,  5, 19,  8,  9],
       [ 8,  5,  9,  7,  9],
       [15, 18,  4, 16,  3],
       [ 6,  6, 19,  6, 13],
       [ 7, 18, 13,  6, 17]])

In [40]:
min = np.min(datas)
max = np.max(datas)

In [44]:
idx_min = datas == min
idx_max = datas == max

In [45]:
result = datas.astype("str")
result

array([['10', '19', '11', '7', '17'],
       ['1', '1', '7', '1', '15'],
       ['10', '19', '8', '13', '12'],
       ['18', '16', '9', '3', '10'],
       ['2', '1', '19', '16', '9']], dtype='<U11')

In [48]:
result[idx_min] = "MIN"
result[idx_max] = "MAX"
result

array([['10', 'MAX', '11', '7', '17'],
       ['MIN', 'MIN', '7', 'MIN', '15'],
       ['10', 'MAX', '8', '13', '12'],
       ['18', '16', '9', '3', '10'],
       ['2', 'MIN', 'MAX', '16', '9']], dtype='<U11')

### 1. linspace, logspace
- linspace : 설정한 범위에서 선형적으로 분할한 위치의 값을 출력
- logspace : 설정한 범위에서 로그로 분할한 위치의 값을 출력

In [51]:
# linspace
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [53]:
# logspace
# log10(x1)=2, log(x2)=3 , log10(x3)= 4
np.logspace(2,4,3)

array([  100.,  1000., 10000.])

In [54]:
# 30세에 연봉이 $100000 이고 60세의 연봉이 $100000 일때
#연봉이 선형으로 증가, 지수함수로 증가하는 두경우에서의 40세, 50세 연봉을 출력

In [55]:
age_30 = 100000
age_60 = 1000000

In [56]:
np.linspace(age_30, age_60,4)

array([ 100000.,  400000.,  700000., 1000000.])

In [60]:
np.logspace(np.log10(age_30), np.log10(age_60), 4)

array([ 100000.        ,  215443.46900319,  464158.88336128,
       1000000.        ])

### 2. numpy random
- seed : 랜덤값을 설정값(랜덤하게 섞이지만 랜덤하게 섞인것이 똑같이 랜덤하게 섞일 수 있도록 함.)
- rand : 균등분포로 랜덤한 값 생성
- randn : 정규분포로 난수를 발생  (뽑힐 확률이 균일 0을 기준으로 실행 0에서 가까운 확률이 뽑힐확률이 높음)
- randint : 균등분포로 정수값을 발생
- suffle : 행렬 데이터를 섞어 줍니다.
- choice : 특정 확률로 데이터를 선택

In [62]:
# seed
np.random.seed(1)
result1 = np.random.randint(10,100,10)

np.random.seed(1)
result2 = np.random.randint(10,100,10)

np.random.seed(2)
result3 = np.random.randint(10,100,10)

result1, result2, result3

(array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([50, 25, 82, 32, 53, 92, 85, 17, 44, 59]))

In [63]:
np.random.rand(10)

array([0.20464863, 0.61927097, 0.29965467, 0.26682728, 0.62113383,
       0.52914209, 0.13457995, 0.51357812, 0.18443987, 0.78533515])

In [64]:
np.random.randn(10)

array([-0.0191305 ,  1.17500122, -0.74787095,  0.00902525, -0.87810789,
       -0.15643417,  0.25657045, -0.98877905, -0.33882197, -0.23618403])

In [66]:
# shuffle
r = np.random.randint(1,10,(3,4))
r

array([[1, 3, 9, 9],
       [3, 7, 6, 7],
       [7, 7, 4, 9]])

In [69]:
np.random.shuffle(r)
r
# 가장 바깥쪽 차원만 바꿔줌
# 다 바꿔주려면 ushave? 사용하면 됨

array([[3, 7, 6, 7],
       [1, 3, 9, 9],
       [7, 7, 4, 9]])

In [72]:
# choice
np.random.choice(5,10, p=[0.1,0,0.4,0.2,0.3])
#numpy는 뒤에 숫자 안들어감 파이썬은 (5,10,2)같이 숫자가 들어감

array([2, 0, 4, 2, 3, 0, 3, 2, 2, 2])

In [74]:
# unique - 유일한 값을 뽑아줌
numbers, counts = np.unique(r, return_counts=True)
print(numbers)
print(counts)

[1 3 4 6 7 9]
[1 2 1 1 4 3]


### 3. 행렬 데이터의 결합
- concatenate

In [75]:
na1 = np.random.randint(10, size=(2, 3))
na2 = np.random.randint(10, size=(3, 2))
na3 = np.random.randint(10, size=(3, 3))

In [76]:
# 세로 결합
na1

array([[1, 9, 2],
       [1, 0, 7]])

In [77]:
na2

array([[1, 8],
       [9, 0],
       [7, 0]])

In [78]:
na3

array([[5, 2, 5],
       [1, 3, 3],
       [1, 8, 6]])

In [96]:
np.concatenate((na2,na1))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [80]:
#세로 결합
np.concatenate((na1,na3))

array([[1, 9, 2],
       [1, 0, 7],
       [5, 2, 5],
       [1, 3, 3],
       [1, 8, 6]])

In [82]:
# 가로 결합
np.concatenate((na2,na3), axis =1)
# axis = 0 -> 세로축, axis = 1 -> 가로축

array([[1, 8, 5, 2, 5],
       [9, 0, 1, 3, 3],
       [7, 0, 1, 8, 6]])

In [84]:
# c_, r_
np.c_[np.array([1,2,3]), np.array([4,5,6])]
    

array([[1, 4],
       [2, 5],
       [3, 6]])

In [86]:
np.r_[np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])

In [87]:
# split, var, std, mean ....