In [67]:
class Crazy_Calculator():
    def __init__(self,num):
        self.num = num
        
    def __add__(self,obj):
        return self.num**3

In [68]:
num1 = Crazy_Calculator(2)
num2 = Crazy_Calculator(3)
num1 + num2

8

In [13]:
import numpy as np


In [29]:
matrix = np.array([[1,7,9],[8,1,5],[6,10,1]])

matrix

array([[ 1,  7,  9],
       [ 8,  1,  5],
       [ 6, 10,  1]])

In [38]:
idx = matrix >=5
matrix[idx] = 0

In [39]:
matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [26]:
idx = matrix > 5
idx

array([[False,  True,  True],
       [ True, False, False],
       [ True,  True, False]])

In [27]:
array2[idx]

array([7, 0, 0, 6, 0])

In [28]:
array2[idx] = 0
array2

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])