### 선형회기 분석
- 프리미어리그 데이터(득점, 실점, 승점)
- 득점, 실점 -> 승점 예측 하는 모델
- scikit-learn 패키지
    - 데이터 마이닝 및 데이터 분석, 모델을 위한 도구
    - 상업적으로 사용이 가능한 오픈소스

In [13]:
import pickle
# 선형회귀 모델
from sklearn import linear_model
# 학습 데이터와 텍스트 데이터를 나눠주는 모듈
from sklearn.model_selection import train_test_split
# 모델을 평가해주는 모듈
from sklearn.metrics import mean_absolute_error

#### 분석 절차
- 데이터 로드
- 데이터 전처리
    - 독립변수(sample data)와 종속변수로 나눠줌
    - 학습 데이터와 테스트 데이터를 나눠줌
- 데이터 분석 : 선형회구 모델
- 성능평가 : MAE(mean absolute error)
- 예측 코드 작성

In [14]:
# 1. 데이터 로드
p_df = pd.read_csv("datas/premierleague.csv")
p_df.tail(1)

name  gf  ga  points
19  West Bromwich Albion  31  56      31

In [15]:
# 2. 데이터 전처리 1 : 독립변수, 종속변수 나누기
df_x = p_df[["gf","ga"]]
df_y = p_df[["points"]]

In [16]:
# 2. 데이터 전처리 2 : 학습데이터와 테스트 데이터로 나누기
train_x, test_x, train_y, test_y = train_test_split(
    df_x,df_y,test_size=0.3, random_state =1) 

# test size 30% train 70% 
# random_state -> random seed 1로 설정

In [17]:
len(train_x)

14

In [18]:
# 3. 데이터 분석 : 선형 회귀 모델
model = linear_model.LinearRegression()

In [19]:
model.fit(train_x, train_y)

LinearRegression()

In [ ]:
# 4. 성능 평가 : MAE


In [ ]:
# test y데이터와 predict y차이에 절댓값을 씌워서 다 더해준 후 n으로 나눠준다.
# 평균적으로 어느정도 차이나는지 결과 알수 있다.

In [22]:
pred_y = model.predict(test_x)
pred_y

array([[80.88065736],
       [40.79778662],
       [50.9467527 ],
       [46.31419247],
       [76.04209484],
       [40.23228639]])

In [24]:
test_y["points"].values 

array([75, 36, 54, 44, 77, 40], dtype=int64)

In [33]:
pred_y = np.around(pred_y.flatten()).astype("int") # flatter 차원을 하나 축소시켜줌
pred_y

array([81, 41, 51, 46, 76, 40])

In [35]:
mae = mean_absolute_error(test_y, pred_y)
round(mae,2)

2.83

In [ ]:
# 수치를 낮춰주기 위해서는 test 데이터를 추가해주거나 컬럼 데이터들을 추가해서 
# 정확하게 만든다.

In [37]:
## 5. 예측 함수
def make_df(gf, ga):
    return pd.DataFrame({"gf":[gf], "ga":[ga]})

In [38]:
make_df(100,20)
#prediction하는 함수는 datafrmae에 넣어줘야 동작을 한다.

gf  ga
0  100  20

In [49]:
gf, ga = 80, 30
result = int(model.predict(make_df(gf,ga)).flatten()[0])
result

83

In [48]:
p_df.head()

name   gf  ga  points
0    Manchester City  106  27     100
1  Manchester United   68  28      81
2  Tottenham Hotspur   74  36      77
3          Liverpool   84  38      75
4            Chelsea   62  38      70

In [51]:
# pickle 파일로 모델 저장하기
with open("datas/p)model.pkl","wb") as f:
    pickle.dump(model, f)
# pickle:파일 인풋 아웃풀 할 떄 파이썬에서 사용해주는 모듈
# pickle을 사용하지 않고 저장 가능하나 pickle이 더 빠르다.

In [53]:
with open("datas/p)model.pkl","rb") as f:
    load_model = pickle.load(f) 

In [54]:
gf, ga = 80, 30
result = int(model.predict(make_df(gf,ga)).flatten()[0])
result

83