In [1]:
# numpy :  파이썬에서 사용하는 과학계산용 패키지
# numpy(c, c++, 포트란) > python

In [ ]:
# 스칼라, 벡터, 메트릭스

In [2]:
# 연산
data1 = np.array([1,2,3])
data2 = np.array([4,5,6])

In [4]:
data1 * 10 # 브로드 캐스팅 : 벡터 * 스칼라

array([10, 20, 30])

In [6]:
data1 * data2 # 같은 형태의 데이터 연산은 같은 위치에 있는 데이터끼리 연산

array([ 4, 10, 18])

In [7]:
# 객체의 데이터 타입 list : +, * 없음
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [ ]:
# 객체의 데이터 타입 ndarray
data1 + data2

In [8]:
type(data1)

numpy.ndarray

In [ ]:
# 학생 성적표 만들기

In [ ]:
# Quiz1. 60 ~ 100 점까지 10점 단위로 10*5 행렬을 만드세요.

In [13]:
datas = np.random.randint(6,11, size = (10,5)) * 10
datas

array([[100,  80, 100,  90,  80],
       [ 80, 100,  90,  60,  70],
       [100,  90,  80,  70,  90],
       [ 60,  90,  80,  90,  60],
       [ 60,  90, 100,  70,  90],
       [ 60,  80,  90,  60,  60],
       [ 90,  90,  90,  60,  90],
       [ 70,  70,  90,  90,  80],
       [ 90,  80,  80, 100, 100],
       [ 90, 100,  80,  60,  80]])

In [ ]:
# quiz 2. 학생별 총점 및 평균 데이터 출력 : ndarray([,,,])

In [16]:
# 총점 
total_point = np.sum(datas, axis = 1)
total_point

array([450, 400, 430, 380, 410, 350, 420, 400, 450, 410])

In [20]:
# 평균 
avg_point = total_point / datas.shape[1]
avg_point

array([90., 80., 86., 76., 82., 70., 84., 80., 90., 82.])

In [ ]:
# quiz 3. 평균이 80점 이상인 학생의 데이터만 출력

In [23]:
point_80 = datas[avg_point>=80]
point_80

array([[100,  80, 100,  90,  80],
       [ 80, 100,  90,  60,  70],
       [100,  90,  80,  70,  90],
       [ 60,  90, 100,  70,  90],
       [ 90,  90,  90,  60,  90],
       [ 70,  70,  90,  90,  80],
       [ 90,  80,  80, 100, 100],
       [ 90, 100,  80,  60,  80]])

In [25]:
# quiz 4. 총점, 평균 데이터를 컬럼으로 붙이기
# np.append(), np.concatenate()

In [29]:
total_point, avg_point

(array([450, 400, 430, 380, 410, 350, 420, 400, 450, 410]),
 array([90., 80., 86., 76., 82., 70., 84., 80., 90., 82.]))

In [31]:
avg_point.reshape(10,1)
# 몇개인지 모르면 avg_point.reshape(-1,1) , -1이 자동으로 계산해서 출력해줌

array([[90.],
       [80.],
       [86.],
       [76.],
       [82.],
       [70.],
       [84.],
       [80.],
       [90.],
       [82.]])

In [24]:
datas

array([[100,  80, 100,  90,  80],
       [ 80, 100,  90,  60,  70],
       [100,  90,  80,  70,  90],
       [ 60,  90,  80,  90,  60],
       [ 60,  90, 100,  70,  90],
       [ 60,  80,  90,  60,  60],
       [ 90,  90,  90,  60,  90],
       [ 70,  70,  90,  90,  80],
       [ 90,  80,  80, 100, 100],
       [ 90, 100,  80,  60,  80]])

In [32]:
# np.c_, np.r_

In [33]:
result = np.c_[datas,total_point,avg_point]
result

array([[100.,  80., 100.,  90.,  80., 450.,  90.],
       [ 80., 100.,  90.,  60.,  70., 400.,  80.],
       [100.,  90.,  80.,  70.,  90., 430.,  86.],
       [ 60.,  90.,  80.,  90.,  60., 380.,  76.],
       [ 60.,  90., 100.,  70.,  90., 410.,  82.],
       [ 60.,  80.,  90.,  60.,  60., 350.,  70.],
       [ 90.,  90.,  90.,  60.,  90., 420.,  84.],
       [ 70.,  70.,  90.,  90.,  80., 400.,  80.],
       [ 90.,  80.,  80., 100., 100., 450.,  90.],
       [ 90., 100.,  80.,  60.,  80., 410.,  82.]])

In [34]:
# quiz 5. 위의 데이터를 데이터 프레임으로 만들기

In [35]:
columns = ["국어","영어","수학","과학","코딩","총점","평균"]

In [38]:
df = pd.DataFrame(result, columns=columns)
df

국어     영어     수학     과학     코딩     총점    평균
0  100.0   80.0  100.0   90.0   80.0  450.0  90.0
1   80.0  100.0   90.0   60.0   70.0  400.0  80.0
2  100.0   90.0   80.0   70.0   90.0  430.0  86.0
3   60.0   90.0   80.0   90.0   60.0  380.0  76.0
4   60.0   90.0  100.0   70.0   90.0  410.0  82.0
5   60.0   80.0   90.0   60.0   60.0  350.0  70.0
6   90.0   90.0   90.0   60.0   90.0  420.0  84.0
7   70.0   70.0   90.0   90.0   80.0  400.0  80.0
8   90.0   80.0   80.0  100.0  100.0  450.0  90.0
9   90.0  100.0   80.0   60.0   80.0  410.0  82.0

In [ ]:
# quiz 6. 각 과목별 평균, 총점 평균, 전체평균을 구해서 마지막 row에 추가

In [42]:
df.loc["평균"] =  df.sum()/ len(df) 
df

국어     영어     수학     과학     코딩     총점    평균
0   100.0   80.0  100.0   90.0   80.0  450.0  90.0
1    80.0  100.0   90.0   60.0   70.0  400.0  80.0
2   100.0   90.0   80.0   70.0   90.0  430.0  86.0
3    60.0   90.0   80.0   90.0   60.0  380.0  76.0
4    60.0   90.0  100.0   70.0   90.0  410.0  82.0
5    60.0   80.0   90.0   60.0   60.0  350.0  70.0
6    90.0   90.0   90.0   60.0   90.0  420.0  84.0
7    70.0   70.0   90.0   90.0   80.0  400.0  80.0
8    90.0   80.0   80.0  100.0  100.0  450.0  90.0
9    90.0  100.0   80.0   60.0   80.0  410.0  82.0
평균   80.0   87.0   88.0   75.0   80.0  410.0  82.0

In [ ]:
# quiz 7. 학생별로 평균이 80점이 넘으면 pass 아니면 fail을 출력하는 컬럼을 추가
# apply, lambda

In [53]:
df["PASS/FAIL"] = df["평균"].apply(lambda x : "PASS" if x>80 else "FAIL" )
df

국어     영어     수학     과학     코딩     총점    평균 PASS/FAIL
0   100.0   80.0  100.0   90.0   80.0  450.0  90.0      PASS
1    80.0  100.0   90.0   60.0   70.0  400.0  80.0      FAIL
2   100.0   90.0   80.0   70.0   90.0  430.0  86.0      PASS
3    60.0   90.0   80.0   90.0   60.0  380.0  76.0      FAIL
4    60.0   90.0  100.0   70.0   90.0  410.0  82.0      PASS
5    60.0   80.0   90.0   60.0   60.0  350.0  70.0      FAIL
6    90.0   90.0   90.0   60.0   90.0  420.0  84.0      PASS
7    70.0   70.0   90.0   90.0   80.0  400.0  80.0      FAIL
8    90.0   80.0   80.0  100.0  100.0  450.0  90.0      PASS
9    90.0  100.0   80.0   60.0   80.0  410.0  82.0      PASS
평균   80.0   87.0   88.0   75.0   80.0  410.0  82.0      PASS

In [56]:
df.columns

Index(['국어', '영어', '수학', '과학', '코딩', '총점', '평균', 'PASS/FAIL'], dtype='object')

In [52]:
df.drop(columns=["총점"])

국어     영어     수학     과학     코딩    평균 PASS/FAIL
0   100.0   80.0  100.0   90.0   80.0  90.0      PASS
1    80.0  100.0   90.0   60.0   70.0  80.0      FAIL
2   100.0   90.0   80.0   70.0   90.0  86.0      PASS
3    60.0   90.0   80.0   90.0   60.0  76.0      FAIL
4    60.0   90.0  100.0   70.0   90.0  82.0      PASS
5    60.0   80.0   90.0   60.0   60.0  70.0      FAIL
6    90.0   90.0   90.0   60.0   90.0  84.0      PASS
7    70.0   70.0   90.0   90.0   80.0  80.0      FAIL
8    90.0   80.0   80.0  100.0  100.0  90.0      PASS
9    90.0  100.0   80.0   60.0   80.0  82.0      PASS
평균   80.0   87.0   88.0   75.0   80.0  82.0      PASS